In [ ]:
# pip install icalendar

In [37]:
pip install recurring-ical-events

Collecting recurring-ical-events
  Downloading recurring_ical_events-3.8.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: icalendar<7.0.0,>=6.1.0 in /opt/homebrew/lib/python3.10/site-packages (from recurring-ical-events) (6.3.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.1 in /opt/homebrew/lib/python3.10/site-packages (from recurring-ical-events) (2.9.0.post0)
Requirement already satisfied: tzdata in /opt/homebrew/lib/python3.10/site-packages (from recurring-ical-events) (2025.2)
Collecting x-wr-timezone<3.0.0,>=1.0.0 (from recurring-ical-events)
  Downloading x_wr_timezone-2.0.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: six>=1.5 in /opt/homebrew/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.8.1->recurring-ical-events) (1.17.0)
Requirement already satisfied: click in /opt/homebrew/lib/python3.10/site-packages (from x-wr-timezone<3.0.0,>=1.0.0->recurring-ical-events) (8.3.1)
Downloading recurring_ical_events-3.8.0-py3-none-any.whl (238 kB)
Downloading x_wr_timezone-2.0.1-py3-none-any.whl (11 kB)
Installing collected packages: x-wr-timezone, recurring-ical-events
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [recurring-ical-events]
Successfully installed recurring-ical-events-3.8.0 x-wr-timezone-2.0.1

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: /opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [26]:
import pandas as pd
import numpy as np

import requests
from icalendar import Calendar

In [57]:
parking_av = pd.read_parquet('../../data/parking_availabilities.parquet')
parkings = pd.read_parquet('../../data/parkings.parquet')
sks_users = pd.read_parquet('../../data/sks_users.parquet')
parking_av[parking_av['parking_id'] == 7].head(30)

,id,parking_id,spaces_left,trend,measured_at,created_at,updated_at
4,5,7,57,-1,2025-02-03 07:51:01+00:00,2025-02-03 07:51:16.246000+00:00,2025-02-03 07:51:16.246000+00:00
9,10,7,57,0,2025-02-03 07:54:01+00:00,2025-02-03 07:54:17.165000+00:00,2025-02-03 07:54:17.165000+00:00
14,15,7,57,0,2025-02-03 07:55:01+00:00,2025-02-03 07:55:16.833000+00:00,2025-02-03 07:55:16.833000+00:00
19,20,7,57,0,2025-02-03 07:56:02+00:00,2025-02-03 07:56:17.041000+00:00,2025-02-03 07:56:17.041000+00:00
24,25,7,57,0,2025-02-03 07:57:01+00:00,2025-02-03 07:57:16.651000+00:00,2025-02-03 07:57:16.651000+00:00
29,30,7,56,-1,2025-02-03 08:00:02+00:00,2025-02-03 08:00:16.648000+00:00,2025-02-03 08:00:16.648000+00:00
34,35,7,56,-1,2025-02-03 08:01:01+00:00,2025-02-03 08:01:18.019000+00:00,2025-02-03 08:01:18.019000+00:00
39,40,7,56,-1,2025-02-03 08:02:02+00:00,2025-02-03 08:02:16.199000+00:00,2025-02-03 08:02:16.199000+00:00
44,45,7,56,-1,2025-02-03 08:03:01+00:00,2025-02-03 08:03:16.790000+00:00,2025-02-03 08:03:16.790000+00:00
49,50,7,55,-1,2025-02-03 08:04:02+00:00,2025-02-03 08:04:10.791000+00:00,2025-02-03 08:04:10.791000+00:00
54,55,7,54,-1,2025-02-03 08:05:01+00:00,2025-02-03 08:05:19.644000+00:00,2025-02-03 08:05:19.644000+00:00
59,60,7,54,-1,2025-02-03 08:06:01+00:00,2025-02-03 08:06:05.320000+00:00,2025-02-03 08:06:05.320000+00:00
64,65,7,53,-1,2025-02-03 08:09:02+00:00,2025-02-03 08:09:17.615000+00:00,2025-02-03 08:09:17.615000+00:00
69,70,7,52,-1,2025-02-03 08:10:02+00:00,2025-02-03 08:10:18.322000+00:00,2025-02-03 08:10:18.322000+00:00
74,75,7,52,-1,2025-02-03 08:12:02+00:00,2025-02-03 08:12:17.520000+00:00,2025-02-03 08:12:17.520000+00:00
79,80,7,52,-1,2025-02-03 08:13:01+00:00,2025-02-03 08:13:17.739000+00:00,2025-02-03 08:13:17.739000+00:00
84,85,7,52,-1,2025-02-03 08:14:02+00:00,2025-02-03 08:14:18.399000+00:00,2025-02-03 08:14:18.399000+00:00
89,90,7,52,0,2025-02-03 08:15:01+00:00,2025-02-03 08:15:13.263000+00:00,2025-02-03 08:15:13.263000+00:00
94,95,7,52,0,2025-02-03 08:16:02+00:00,2025-02-03 08:16:15.222000+00:00,2025-02-03 08:16:15.222000+00:00
99,100,7,52,0,2025-02-03 08:17:01+00:00,2025-02-03 08:17:16.337000+00:00,2025-02-03 08:17:16.337000+00:00
104,105,7,52,0,2025-02-03 08:18:01+00:00,2025-02-03 08:18:16.883000+00:00,2025-02-03 08:18:16.883000+00:00
109,110,7,51,-1,2025-02-03 08:24:02+00:00,2025-02-03 08:24:16.511000+00:00,2025-02-03 08:24:16.511000+00:00
114,115,7,51,-1,2025-02-03 08:26:01+00:00,2025-02-03 08:26:17.272000+00:00,2025-02-03 08:26:17.272000+00:00
119,120,7,51,-1,2025-02-03 08:27:02+00:00,2025-02-03 08:27:17.235000+00:00,2025-02-03 08:27:17.235000+00:00
124,125,7,51,-1,2025-02-03 08:28:01+00:00,2025-02-03 08:28:16.544000+00:00,2025-02-03 08:28:16.544000+00:00
129,130,7,51,-1,2025-02-03 08:29:02+00:00,2025-02-03 08:29:17.076000+00:00,2025-02-03 08:29:17.076000+00:00
134,135,7,51,0,2025-02-03 08:31:02+00:00,2025-02-03 08:31:05.570000+00:00,2025-02-03 08:31:05.570000+00:00
139,140,7,51,0,2025-02-03 08:32:01+00:00,2025-02-03 08:32:05.929000+00:00,2025-02-03 08:32:05.929000+00:00
144,145,7,51,0,2025-02-03 08:33:02+00:00,2025-02-03 08:33:15.766000+00:00,2025-02-03 08:33:15.766000+00:00
149,150,7,50,-1,2025-02-03 08:34:01+00:00,2025-02-03 08:34:16.389000+00:00,2025-02-03 08:34:16.389000+00:00

In [28]:
parkings.head()

,id,symbol,type,name,open_hour,close_hour,places,geo_lan,geo_lat,is_active,is_visible,address,created_at,updated_at
0,7,E01,O,Architektura,06:00:00,22:30:00,75,17.054167,51.118736,True,True,"Bolesława Prusa 53/55, 50-317 Wrocław\r\n",2025-02-03 07:51:16.241000+00:00,2025-12-06 19:46:06.731000+00:00
1,4,WRO,O,Parking Wrońskiego,06:00:00,22:00:00,207,17.055565,51.108963,True,True,"Hoene-Wrońskiego 10, 50-376 Wrocław",2025-02-03 07:51:16.185000+00:00,2025-12-06 19:46:06.218000+00:00
2,2,C13,O,Polinka,None,None,54,17.058468,51.107390,True,True,"wybrzeże Stanisława Wyspiańskiego 25, 50-370 W...",2025-02-03 07:51:16.210000+00:00,2025-12-06 19:46:06.343000+00:00
3,5,D20,O,D20 - D21,06:00:00,22:30:00,76,17.059677,51.110050,True,True,"Janiszewskiego 8, 50-372 Wrocław\r\n",2025-02-03 07:51:16.222000+00:00,2025-12-06 19:46:06.478000+00:00
4,6,GEO-L,O,GEO LO1 Geocentrum,06:00:00,22:30:00,301,17.055334,51.104164,True,True,"Na Grobli 15, 50-421 Wrocław\r\n",2025-02-03 07:51:16.232000+00:00,2025-12-06 19:46:06.602000+00:00

In [72]:
sks_users

,external_timestamp,active_users,moving_average_21,created_at,updated_at
0,2025-02-03 05:25:00+00:00,1,0,2025-02-03 10:25:00.606927+00:00,2025-02-03 22:59:00.896225+00:00
1,2025-02-03 05:30:00+00:00,1,1,2025-02-03 10:25:00.606927+00:00,2025-02-03 22:59:00.896225+00:00
2,2025-02-03 05:35:00+00:00,2,1,2025-02-03 10:25:00.606927+00:00,2025-02-03 22:59:00.896225+00:00
3,2025-02-03 05:40:00+00:00,2,1,2025-02-03 10:25:00.606927+00:00,2025-02-03 22:59:00.896225+00:00
4,2025-02-03 05:45:00+00:00,3,1,2025-02-03 10:25:00.606927+00:00,2025-02-03 22:59:00.896225+00:00
...,...,...,...,...,...
77626,2025-12-06 22:35:00+00:00,0,11,2025-12-05 23:00:00.346208+00:00,2025-12-06 19:42:00.193069+00:00
77627,2025-12-06 22:40:00+00:00,0,11,2025-12-05 23:00:00.346208+00:00,2025-12-06 19:42:00.193069+00:00
77628,2025-12-06 22:45:00+00:00,0,10,2025-12-05 23:00:00.346208+00:00,2025-12-06 19:42:00.193069+00:00
77629,2025-12-06 22:50:00+00:00,0,10,2025-12-05 23:00:00.346208+00:00,2025-12-06 19:42:00.193069+00:00
77630,2025-12-06 22:55:00+00:00,0,10,2025-12-05 23:00:00.346208+00:00,2025-12-06 19:42:00.193069+00:00

In [68]:
url = "https://calendar.google.com/calendar/ical/9ke30hbjjke60u5jbii42g2rpo@group.calendar.google.com/public/basic.ics"

resp = requests.get(url, timeout=30)
resp.raise_for_status()          # raises if 4xx/5xx
cal = Calendar.from_ical(resp.content)

events = []
for ev in cal.walk("VEVENT"):
    events.append({
        "uid": str(ev.get("uid", "")),
        "summary": str(ev.get("summary", "")),
        "start": ev.decoded("dtstart"),  # date or datetime
        "end": ev.decoded("dtend") if ev.get("dtend") else None,
        "location": str(ev.get("location", "")),
    })
events_df = pd.DataFrame(events)
# (optional but recommended) make timestamps consistent for parquet
events_df["start"] = pd.to_datetime(events_df["start"], utc=True, errors="coerce")
events_df["end"]   = pd.to_datetime(events_df["end"],   utc=True, errors="coerce")

In [69]:
events_df.to_parquet("../../data/pwr_events.parquet", index=False)

In [71]:
oko = pd.read_parquet('../../data/pwr_events.parquet')
oko.head(50)

,uid,summary,start,end,location
0,64etqju29vmbvvmfnrdrdcbce1@google.com,Dzień Studenta na W-6,2023-11-17 00:00:00+00:00,2023-11-18 00:00:00+00:00,
1,6th3id9p68p6abb160s66b9k6gqmabb1c9i38bb3cphjeo...,[Studencka Dawka Kultury] Wyjście na Fantastyc...,2018-11-16 18:00:00+00:00,2018-11-16 21:00:00+00:00,
2,3molmc2sfn4jbhi8j55gjnrgfs@google.com,II Wrocławskie Studenckie Sympozjum Chemiczne...,2013-04-13 08:00:00+00:00,2013-04-13 16:00:00+00:00,
3,cdh3ec9pcpj30b9l74p6ab9k6oo3ibb16ss38bb568rj2c...,ATP,2019-10-15 00:00:00+00:00,2019-10-17 00:00:00+00:00,
4,5e5mi83jagqmb7iarfb593pmjh@google.com,Mikołajki W7 - cukierki na kampusie,2017-12-06 00:00:00+00:00,2017-12-07 00:00:00+00:00,
5,76vfkm0394jkf2l581k2vt5tm5@google.com,Szef & Adapciak,2021-12-10 00:00:00+00:00,2021-12-13 00:00:00+00:00,
6,va52qaksnchghtfbgpijeeci30@google.com,Tłuste PWr Party [ZPS],2013-02-07 20:00:00+00:00,2013-02-07 23:00:00+00:00,Daytona
7,4ps2o2d2c2i6ka1algugd04t0c@google.com,Geosiata,2025-05-28 00:00:00+00:00,2025-05-29 00:00:00+00:00,
8,tmoioa9kpgc99ott0mcsksuk5o@google.com,3maj poziom - browar,2024-12-11 00:00:00+00:00,2024-12-12 00:00:00+00:00,
9,D6D031A4-7566-4ABC-939F-D20FC805DB6F,Grill u Marty i Piotrusia na DZIAŁCE,2040-06-13 00:00:00+00:00,2040-06-14 00:00:00+00:00,
10,006f6p02gc4acej4tj930a4rag@google.com,PWr Party na zakończenie VII semestru,2012-12-13 20:00:00+00:00,2012-12-13 23:00:00+00:00,Klub Teatr
11,tbapse9bfso5eeafjb9mhi9dtg@google.com,POSIEDZENIE PARLAMENTU [ZPS],2012-11-27 18:00:00+00:00,2012-11-27 20:00:00+00:00,Nowa Sala Senatu / A1
12,4hktugehikop9fpfcvr1neaa87@google.com,BIMaction,2019-05-10 00:00:00+00:00,2019-05-13 00:00:00+00:00,
13,66n6fn1l1gqcpnghfvvmatpnvi@google.com,Wieczór Gier Planszowych,2022-12-12 17:00:00+00:00,2022-12-12 23:00:00+00:00,Klubokawiarnia SKS
14,720plvrgq4244p1649uirso2nt@google.com,Posiedzenie PSPWr,2021-05-11 17:15:00+00:00,2021-05-11 20:15:00+00:00,
15,t17b05ij5giq0p9vpt601erjag@google.com,Świąteczne Planszówki W6,2024-12-10 00:00:00+00:00,2024-12-11 00:00:00+00:00,
16,kq22l00sp855qfgq2ukk9fa3a4@google.com,Witajcie w naszej bajce - Dzień Dziecka na W6,2017-06-01 07:00:00+00:00,2017-06-01 13:00:00+00:00,"Geocentrum, Na Grobli 15/15, 50-421 Wrocław, P..."
17,590aehelmdrgks26h34709ofbd@google.com,Dom Strachu (Kultura),2024-03-12 00:00:00+00:00,2024-03-13 00:00:00+00:00,"Hoene-Wrońskiego 10, 50-376 Wrocław, Polska"
18,60q3aor26ssj4bb16li66b9kc5hm6b9p6pj32bb2c8pm8e...,Rejs Samorządowca,2019-06-06 17:00:00+00:00,2019-06-06 20:00:00+00:00,
19,6dim8eb56ssj6bb4ckp36b9k6th62bb16di3ab9g68om2p...,ARCHIgrill W1,2022-06-04 14:00:00+00:00,2022-06-04 18:00:00+00:00,
20,11trtr0d70h9biepbveg8rlpph@google.com,Juwenalia przejmują niepolda,2018-03-26 19:00:00+00:00,2018-03-26 22:00:00+00:00,
21,6mpntfnutjudpbks1ho86jsbh0@google.com,Wyjazd Szkoleniowo-Integracyjny Sekcji Organiz...,2021-10-22 00:00:00+00:00,2021-10-25 00:00:00+00:00,"Ośrodek Wypoczynkowy Marysieńka, Wodna 3, 57-3..."
22,a5m37pksd8amhpcqccjgs15upk@google.com,Rejs W2xW3,2025-06-05 00:00:00+00:00,2025-06-06 00:00:00+00:00,
23,caof5fdofaitoiuajdu88ekjc0@google.com,Mechaniczny Start W10 10/10,2013-10-10 19:00:00+00:00,2013-10-11 03:00:00+00:00,Klub Eter
24,7jni3oblrfami84v44lt6jfn3j@google.com,ARCHIkultura W1 - Muzyka Tatr,2020-05-29 17:30:00+00:00,2020-05-29 18:30:00+00:00,
25,1ae6hootos2206nrqie03892ai@google.com,Rejs W6xW9,2026-05-28 00:00:00+00:00,2026-05-29 00:00:00+00:00,
26,66qfj8reqs5vucd171dt2bkm80@google.com,W5 Party- After Rajd Elektryka,2014-04-09 19:00:00+00:00,2014-04-10 02:00:00+00:00,"Teatr Klub Muzyczny, Oławska, Wrocław, Polska"
27,4jich37tl140hd3em7ujk60sf7@google.com,Wyjazd integracyjny - W3,2017-12-01 00:00:00+00:00,2017-12-04 00:00:00+00:00,
28,6srj6ob6cgr3ib9j6kqjgb9kc5hm6b9p65hmab9jc9ijip...,Wydziałówka W3 x W4,2023-05-18 00:00:00+00:00,2023-05-19 00:00:00+00:00,
29,2htp24ouc7ik6a2ff05uvvh1k5@google.com,Dziki Bajer,2025-06-06 00:00:00+00:00,2025-06-07 00:00:00+00:00,"Students Club Bajer, Edwarda Wittiga 6, 50-438..."
30,jpu1epuar6pi8nq6ovnsa0kb0s@google.com,PWr Party - Dzień dziecka,2017-06-01 19:00:00+00:00,2017-06-02 01:00:00+00:00,
31,7nph7pvmn5hmk0s6kl6cq42j4j@google.com,Tydzień Zdrowia W11,2023-05-29 00:00:00+00:00,2023-06-05 00:00:00+00:00,
32,6gqj4pb56phm2b9m65h66b9k64pj8bb268pm4bb46pgj2o...,Dzień Otwarty PWr,2025-04-11 00:00:00+00:00,2025-04-12 00:00:00+00:00,
33,alfrvqttarpsshoq5gj9ik7htg@google.com,Spotkanie informacyjne Kursu Taternictwa Jaski...,2014-03-05 18:00:00+00:00,2014-03-05 19:30:00+00:00,"Sala 2.17, budynek C-13 PWr (ul. Wybrzeże Wysp..."
34,c4bq64o9otg65rjgd83l4jqk48@google.com,W10 & W12 Party,2014-05-23 19:00:00+00:00,2014-05-24 03:00:00+00:00,Klub Konqrencja
35,fdtupo9pk4mf9dkdkef5lihgco@google.com,Rajd W2xW3xW6,2024-04-26 10:00:00+00:00,2024-04-28 14:00:00+00:00,
36,530t57t95f5v2qe1gunvtsmpge@google.com,Strefa Kibica Politechniki Wrocławskiej - Mist...,2022-11-30 19:00:00+00:00,2022-11-30 21:00:00+00:00,"Strefa Kultury Studenckiej, Hoene-Wrońskiego 1..."
37,3mr3cfucp5tm2v8jb4uapmusal@google.com,Konferencja Dydaktyczna,2023-12-15 00:00:00+00:00,2023-12-18 00:00:00+00:00,
38,c8q3go9lcgom2b9k6grj8b9k6gojgb9pc4s3gb9mccsj0d...,Łyżwy z W8,2017-12-05 17:00:00+00:00,2017-12-05 18:00:00+00:00,
39,ccq6cohp71i3ebb2cop6cb9k6ss6abb16os6cb9h74sm4c...,Dni Zero PWr,2019-09-27 00:00:00+00:00,2019-09-30 00:00:00+00:00,
40,6kq3epj1c8qjgbb1c8pmcb9k74om8bb1cgsjibb264r62c...,Bal inżyniera W3,2019-02-15 00:00:00+00:00,2019-02-16 00:00:00+00:00,
41,clhjco9p6pijib9g74r6ab9k70om8bb16hj3abb2c4o3io...,I love PWr,2024-10-01 00:00:00+00:00,2024-10-02 00:00:00+00:00,
42,69j38p1o60qjab9pc9ijib9kcgq3ibb168o30b9mcoqjcp...,SOK - Pani Furia [Teatr Współczesny],2019-04-07 16:00:00+00:00,2019-04-07 18:00:00+00:00,
43,a1tnbjb1slr1ff5a1o3k8bgot8@google.com,Gra samorządowca,2025-04-24 00:00:00+00:00,2025-04-25 00:00:00+00:00,
44,2n3lvbt1rgait5oflvvqu94qeg@google.com,Mikołajki PWr,2013-12-06 20:00:00+00:00,2013-12-07 03:00:00+00:00,klub Daytona
45,05k44bkabpsavvuf19svs6stfi@google.com,PWr Party,2019-10-01 19:00:00+00:00,2019-10-02 02:00:00+00:00,"Mundo 71 Music Club, pasaż Niepolda, 52-007 Wr..."
46,c5hm2phjcgpjabb270r3gb9k74q34bb2cdim6b9gckp6ce...,Parlament,2019-04-23 17:00:00+00:00,2019-04-23 21:30:00+00:00,
47,4m62i5sdg5cup0f04alnf8uuij@google.com,ARCHIkultura - W1 NFM - Siedem bram Jerozolimy,2020-03-13 18:30:00+00:00,2020-03-13 19:30:00+00:00,
48,643thoegg987lg9f35cupf4rvc@google.com,Rejs W10,2025-05-27 00:00:00+00:00,2025-05-28 00:00:00+00:00,
49,ddlshs0jsdgugpvi12j92h90og@google.com,Bal Karnawałowy PWr,2019-03-02 19:00:00+00:00,2019-03-03 02:00:00+00:00,

In [40]:
import requests
from icalendar import Calendar
import recurring_ical_events
from datetime import datetime, timezone

url = "https://calendar.google.com/calendar/ical/9ke30hbjjke60u5jbii42g2rpo@group.calendar.google.com/public/basic.ics"
cal = Calendar.from_ical(requests.get(url, timeout=30).content)

start = datetime(2025, 1, 1, tzinfo=timezone.utc)
end   = datetime(2025, 12, 31, tzinfo=timezone.utc)

occurrences = recurring_ical_events.of(cal).between(start, end)

[(e.get("summary"), e.decoded("dtstart")) for e in occurrences[:10]]

[(vText(b'SDK - dzika Azja'),
  datetime.datetime(2025, 1, 9, 18, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Warsaw'))),
 (vText(b'P\xc3\xb3\xc5\x82metek chemika'), datetime.date(2025, 4, 10)),
 (vText(b'Rejs W8'), datetime.date(2025, 6, 12)),
 (vText(b'Bajer on Fire II '),
  datetime.datetime(2025, 4, 30, 20, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Warsaw'))),
 (vText(b'Rajd W4'), datetime.date(2025, 10, 17)),
 (vText(b'Bal W2xW7'),
  datetime.datetime(2025, 3, 22, 19, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Warsaw'))),
 (vText(b'Dzie\xc5\x84 Ziemi'), datetime.date(2025, 4, 26)),
 (vText(b'Impreza - Bajer'),
  datetime.datetime(2025, 3, 14, 21, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Warsaw'))),
 (vText(b'Zlecenie: Zmora studenckiego traktu - Rajd Wiosenny W9'),
  datetime.date(2025, 4, 25)),
 (vText(b'"Bagno" Rajd W6xW8xW12'), datetime.date(2025, 5, 9))]

In [ ]:
occurrences_df = pd.DataFrame([{

[VEVENT({'DTSTART': vDDDTypes(2025-01-09 18:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-01-09 21:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'ujgktetv1rstb5pbr0rdqrk5pk@google.com'), 'CREATED': vDDDTypes(2024-12-05 17:48:14+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2024-12-05 17:48:14+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'SDK - dzika Azja'), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-01-09 18:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-10, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-04-11, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'71qkbgn0ihdjl9pigrkiei6jqg@google.com'), 'CREATED': vDDDTypes(2025-01-13 16:09:45+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-13 16:09:45+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'P\xc3\xb3\xc5\x82metek chemika'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-04-10, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-06-12, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-06-13, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'60k0vde3ruejm5mbhu4jd2c4pp@google.com'), 'CREATED': vDDDTypes(2024-10-02 10:40:36+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-03-25 20:06:27+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Rejs W8'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-06-12, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-30 20:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-04-30 23:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'5g1nlglajaooivool0b5d0mn1s@google.com'), 'CREATED': vDDDTypes(2025-01-05 17:33:19+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-30 19:15:49+00:00, Parameters({})), 'LOCATION': vText(b'Students Club Bajer\\, Edwarda Wittiga 6\\, 50-438 Wroc\xc5\x82aw\\, Poland'), 'SEQUENCE': 1, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Bajer on Fire II '), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-04-30 20:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-10-17, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-10-20, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'7va5u7t5jft1b9jrmmfcn525dr@google.com'), 'CREATED': vDDDTypes(2025-02-20 19:35:56+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-02-20 19:35:56+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Rajd W4'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-10-17, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-03-22 19:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-03-22 23:55:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'gcf3k33ev390ff83egl2psc4so@google.com'), 'CREATED': vDDDTypes(2025-02-20 12:29:59+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-02-20 12:29:59+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Bal W2xW7'), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-03-22 19:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-26, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-04-27, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'9jh90vis6anj49flvqq3l7n9vk@google.com'), 'CREATED': vDDDTypes(2025-01-16 22:14:42+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-16 22:14:42+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Dzie\xc5\x84 Ziemi'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-04-26, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-03-14 21:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-03-15 04:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'27n4fm2k2b1cte06978ff0gohd@google.com'), 'CREATED': vDDDTypes(2025-01-08 21:21:33+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-30 19:12:26+00:00, Parameters({})), 'LOCATION': vText(b'Student Culture Zone\\, Hoene-Wro\xc5\x84skiego 10\\, 50-376 Wroc\xc5\x82aw\\, Poland'), 'SEQUENCE': 1, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Impreza - Bajer'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-03-14 21:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-25, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-04-28, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'75ijep9m60ojcbb160r3cb9k68p62bb26cs34b9m6dim8pho64rjedhic4@google.com'), 'CREATED': vDDDTypes(2024-10-09 17:31:25+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-04-16 08:25:18+00:00, Parameters({})), 'SEQUENCE': 1, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Zlecenie: Zmora studenckiego traktu - Rajd Wiosenny W9'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-04-25, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-05-09, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-05-12, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'42a26bb1djf8abh4e31ds3089t@google.com'), 'CREATED': vDDDTypes(2024-10-02 10:40:21+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-02-10 14:33:55+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'"Bagno" Rajd W6xW8xW12'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-05-09, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-03-27, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-03-28, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'124jarfsv8k1kimslnicnoktlr@google.com'), 'CREATED': vDDDTypes(2024-11-05 17:47:45+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-16 15:55:30+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Wydzia\xc5\x82\xc3\xb3wka W4xW11xW13'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-03-27, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-02-14, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-02-15, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'349pc68b8i53benaeqebk607lp@google.com'), 'CREATED': vDDDTypes(2024-10-02 10:39:51+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2024-10-26 19:55:21+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Bal W4xW8'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-02-14, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-06-11, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-06-12, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'0a16ht0qtt7s14tt8rodilc084@google.com'), 'CREATED': vDDDTypes(2025-05-13 21:16:25+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-05-13 21:16:25+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Rejs W13'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-06-11, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-03-13 20:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-03-13 23:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b't3s1oq9p13ts1dcbksja2ki4ec@google.com'), 'CREATED': vDDDTypes(2024-12-18 15:46:21+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2024-12-18 15:46:21+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Wydzia\xc5\x82\xc3\xb3wka W2xW14'), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-03-13 20:00:00+01:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-06-04, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-06-05, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'7ltjns7lq9549h0po9v4fss688@google.com'), 'CREATED': vDDDTypes(2025-03-06 15:02:14+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-03-06 15:02:14+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Volvo Wednesday - W4'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-06-04, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-06-12 22:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-06-13 04:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'5oh4b1hosfrqrb2h5csi0dpocv@google.com'), 'CREATED': vDDDTypes(2025-01-07 16:09:41+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-05-13 11:45:42+00:00, Parameters({})), 'SEQUENCE': 4, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'PWr Party'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-06-12 22:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-10-10, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-10-11, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'70sjicr26pij6b9h71ijib9k6sqjibb1clgj4b9hcgsjidb36sr32o9jco@google.com'), 'RECURRENCE-ID': vDDDTypes(2025-10-10, Parameters({'VALUE': 'DATE'})), 'CREATED': vDDDTypes(2018-04-29 12:03:35+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-09-15 17:32:06+00:00, Parameters({})), 'SEQUENCE': 1, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Urodziny Wydzia\xc5\x82 Mechaniczny 10.10'), 'TRANSP': vText(b'TRANSPARENT')}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-03 09:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-04-03 20:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'2tbpl6t1s84970nskp51rq4ocs@google.com'), 'CREATED': vDDDTypes(2024-11-19 10:14:04+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2024-11-19 10:14:04+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Targi Pracy Waffle Engineer 5'), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-04-03 09:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-05-28, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-05-29, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'4ps2o2d2c2i6ka1algugd04t0c@google.com'), 'CREATED': vDDDTypes(2025-03-12 07:28:43+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-04-28 14:21:10+00:00, Parameters({})), 'SEQUENCE': 1, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Geosiata'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-05-28, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-05-08, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-05-09, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'1m0ufur49lkbkvmcnmbrbcpcp5@google.com'), 'CREATED': vDDDTypes(2024-11-04 12:06:24+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-21 08:31:42+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'After Rajdu W1xW4xW14'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-05-08, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-05-29, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-05-30, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'6blfi0ol0if0n1p5s8qup2u653@google.com'), 'CREATED': vDDDTypes(2025-03-06 15:02:46+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-03-06 15:02:46+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Wydzia\xc5\x82\xc3\xb3wka W4xW7'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-05-29, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-07 07:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-04-11 08:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'2k51pgbci3c0g8lk3s7fnecfkg@google.com'), 'CREATED': vDDDTypes(2024-12-09 12:24:11+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2024-12-09 16:06:13+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Tydzie\xc5\x84 zdrowia '), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-04-07 07:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-07 19:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-04-07 20:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'c9hmadho6sr3ib9lcop6cb9kchi68b9o68r3eb9m6cp30phg6lj34p9p64@google.com'), 'CREATED': vDDDTypes(2025-03-21 13:29:16+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-03-21 13:29:16+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Spotkanie Uczelnianych Organizacji Studenckich '), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-04-07 19:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-24, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-04-25, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'a1tnbjb1slr1ff5a1o3k8bgot8@google.com'), 'CREATED': vDDDTypes(2025-03-20 13:38:06+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-04-30 13:03:53+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Gra samorz\xc4\x85dowca'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-04-24, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-01 17:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-04-01 23:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'oa2q3alfvckcruj37qglp32ifg@google.com'), 'CREATED': vDDDTypes(2025-01-16 22:13:57+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-16 22:13:57+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'WarsztaTeki'), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-04-01 17:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-12-01, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-12-02, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'60qmcp9n65h36b9n64s3gb9k75h38bb1clh3ibb568r38d9k6lgm6oj470@google.com'), 'CREATED': vDDDTypes(2025-08-19 21:19:18+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-08-19 21:19:19+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'G\xc3\xb3rnicza Krew'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-12-01, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-04-29, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-04-30, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'c2isr8ion61fqgr1lktc874rik@google.com'), 'CREATED': vDDDTypes(2025-03-27 10:58:15+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-04-07 17:29:37+00:00, Parameters({})), 'SEQUENCE': 1, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Kino plenerowe - W3xW13'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-04-29, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-10-09, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-10-10, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'7vg9qmidn2q8a02ft379iqa9m0@google.com'), 'CREATED': vDDDTypes(2025-09-17 09:50:07+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-09-17 09:50:08+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Before Rajdu W1xW4xW10 & Urodziny W10'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-10-09, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-10-24, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-10-27, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'019dcajmop6sjgjjqdemc6ujgc@google.com'), 'CREATED': vDDDTypes(2025-01-18 13:47:04+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-06-07 16:04:35+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Rajd jesienny W3xW9xW13'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-10-24, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-06-07, Parameters({'VALUE': 'DATE'})), 'DTEND': vDDDTypes(2025-06-09, Parameters({'VALUE': 'DATE'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'2bhdvphvjp93epl7qv0d4t5ccs@google.com'), 'CREATED': vDDDTypes(2025-01-20 20:12:43+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-04-16 14:18:02+00:00, Parameters({})), 'SEQUENCE': 2, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'Liga PWr'), 'TRANSP': vText(b'TRANSPARENT'), 'RECURRENCE-ID': vDDDTypes(2025-06-07, Parameters({'VALUE': 'DATE'}))}),
 VEVENT({'DTSTART': vDDDTypes(2025-05-13 17:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTEND': vDDDTypes(2025-05-13 23:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'})), 'DTSTAMP': vDDDTypes(2025-12-09 13:13:21+00:00, Parameters({})), 'UID': vText(b'neocp2f2utuam5ihgpsm6me008@google.com'), 'CREATED': vDDDTypes(2025-01-16 22:15:30+00:00, Parameters({})), 'LAST-MODIFIED': vDDDTypes(2025-01-16 22:15:30+00:00, Parameters({})), 'SEQUENCE': 0, 'STATUS': vText(b'CONFIRMED'), 'SUMMARY': vText(b'WarsztaTeki'), 'TRANSP': vText(b'OPAQUE'), 'RECURRENCE-ID': vDDDTypes(2025-05-13 17:00:00+02:00, Parameters({'TZID': 'Europe/Warsaw'}))}),

In [47]:
def make_lag(df, core_column, lag=[1], group_cols=None):
    """
    Tworzy kolumny opóźnień (lag) dla wskazanej tabeli i kolumny.

    Parametry:
    - df : DataFrame wejściowy
    - core_column : nazwa kolumny, dla której liczymy lag
    - lag : lista wartości opóźnienia (np. [1, 7])
    - group_cols : lista kolumn do grupowania (opcjonalnie)

    Zwraca:
    - DataFrame z nowymi kolumnami *_lag_{value}
    """
    df = df.copy()

    # Jeśli podano kolumny grupujące
    if group_cols:
        grouped = df.groupby(group_cols)[core_column]

    for value in lag:
        col_name = f'{core_column}_lag_{value}'  # nazwa nowej kolumny
        if group_cols:
            df[col_name] = grouped.shift(value)  # lag wewnątrz grup
        else:
            df[col_name] = df[core_column].shift(value)  # lag bez grupowania
    return df


def make_rolling(df, core_column, rollag=[1], window=[7],
                 rolling_stats=['mean', 'std', 'max', 'min', 'sum'], group_cols=None):
    """
    Tworzy statystyki kroczące (rolling window) dla wskazanej tabeli i kolumny.

    Parametry:
    - df : DataFrame wejściowy
    - core_column : kolumna bazowa
    - rollag : lista opóźnień przed rozpoczęciem rolling (np. [1, 7])
    - window : lista długości okna (np. [7, 14])
    - rolling_stats : lista statystyk do obliczenia ('mean', 'std', 'max', 'min', 'sum')
    - group_cols : lista kolumn do grupowania (opcjonalnie)

    Zwraca:
    - DataFrame z nowymi kolumnami *_roll{window}_{stat}_lag{value}
    """
    df = df.copy()
    # Jeśli podano kolumny grupujące
    if group_cols:
        grouped = df.groupby(group_cols)[core_column]

    for stat in rolling_stats:
        for value in rollag:
            for w in window:
                col_name = f'{core_column}_roll{w}_{stat}_lag{value}'
                if group_cols:
                    # obliczanie rolling w ramach każdej grupy po wcześniejszym przesunięciu
                    df[col_name] = grouped.transform(lambda x: x.shift(value).rolling(w).agg(stat))
                else:
                    df[col_name] = df[core_column].shift(value).rolling(window=w).agg(stat)

    return df


def make_expanding(df, core_column, explag=[1],
                   exp_stats=['mean', 'std', 'max', 'min', 'sum'], group_cols=None):
    """
    Tworzy statystyki narastające (expanding window) dla wskazanej kolumny.

    Parametry:
    - df : DataFrame wejściowy
    - core_column : kolumna bazowa
    - explag : lista opóźnień przed rozpoczęciem expanding (np. [1])
    - exp_stats : lista statystyk do obliczenia ('mean', 'std', 'max', 'min', 'sum')
    - group_cols : lista kolumn do grupowania (opcjonalnie)

    Zwraca:
    - DataFrame z nowymi kolumnami *_exp_{stat}_lag{value}
    """
    df = df.copy()

    if group_cols:
        grouped = df.groupby(group_cols)[core_column]

    for stat in exp_stats:
        for value in explag:
            col_name = f'{core_column}_exp_{stat}_lag{value}'
            if group_cols:
                # statystyki expanding w ramach każdej grupy po wcześniejszym przesunięciu
                df[col_name] = grouped.transform(lambda x: x.shift(value).expanding().agg(stat))
            else:
                df[col_name] = df[core_column].shift(value).expanding().agg(stat)

    return df

In [51]:
parking_av_lagged

,id,parking_id,spaces_left,trend,measured_at,created_at,updated_at,spaces_left_lag_1,spaces_left_lag_7,spaces_left_lag_14
0,1,4,0,0,2025-02-03 07:51:01+00:00,2025-02-03 07:51:16.203000+00:00,2025-02-03 07:51:16.203000+00:00,NaN,NaN,NaN
1,2,2,4,0,2025-02-03 07:51:01+00:00,2025-02-03 07:51:16.217000+00:00,2025-02-03 07:51:16.217000+00:00,NaN,NaN,NaN
2,3,5,0,0,2025-02-03 07:51:01+00:00,2025-02-03 07:51:16.228000+00:00,2025-02-03 07:51:16.228000+00:00,NaN,NaN,NaN
3,4,6,169,-2,2025-02-03 07:51:01+00:00,2025-02-03 07:51:16.237000+00:00,2025-02-03 07:51:16.237000+00:00,NaN,NaN,NaN
4,5,7,57,-1,2025-02-03 07:51:01+00:00,2025-02-03 07:51:16.246000+00:00,2025-02-03 07:51:16.246000+00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1826524,1826553,4,132,0,2025-12-07 14:53:01+00:00,2025-12-07 14:53:05.822000+00:00,2025-12-07 14:53:05.822000+00:00,132.0,131.0,131.0
1826525,1826554,2,42,0,2025-12-07 14:53:01+00:00,2025-12-07 14:53:05.976000+00:00,2025-12-07 14:53:05.976000+00:00,42.0,42.0,42.0
1826526,1826555,5,14,0,2025-12-07 14:53:01+00:00,2025-12-07 14:53:06.099000+00:00,2025-12-07 14:53:06.099000+00:00,14.0,14.0,14.0
1826527,1826556,6,261,0,2025-12-07 14:53:01+00:00,2025-12-07 14:53:06.220000+00:00,2025-12-07 14:53:06.220000+00:00,261.0,261.0,261.0
1826528,1826557,7,84,0,2025-12-07 14:53:01+00:00,2025-12-07 14:53:06.341000+00:00,2025-12-07 14:53:06.341000+00:00,84.0,84.0,84.0

In [64]:
parking_av_lagged = make_lag(parking_av, 'spaces_left', lag=[1,7,14], group_cols=['parking_id'])
parking_av_lagged[parking_av_lagged['parking_id'] == 7][['spaces_left', 'measured_at', 'created_at', 'updated_at', 'spaces_left_lag_1', 'spaces_left_lag_7', 'spaces_left_lag_14']].head(20)

,spaces_left,measured_at,created_at,updated_at,spaces_left_lag_1,spaces_left_lag_7,spaces_left_lag_14
4,57,2025-02-03 07:51:01+00:00,2025-02-03 07:51:16.246000+00:00,2025-02-03 07:51:16.246000+00:00,NaN,NaN,NaN
9,57,2025-02-03 07:54:01+00:00,2025-02-03 07:54:17.165000+00:00,2025-02-03 07:54:17.165000+00:00,57.0,NaN,NaN
14,57,2025-02-03 07:55:01+00:00,2025-02-03 07:55:16.833000+00:00,2025-02-03 07:55:16.833000+00:00,57.0,NaN,NaN
19,57,2025-02-03 07:56:02+00:00,2025-02-03 07:56:17.041000+00:00,2025-02-03 07:56:17.041000+00:00,57.0,NaN,NaN
24,57,2025-02-03 07:57:01+00:00,2025-02-03 07:57:16.651000+00:00,2025-02-03 07:57:16.651000+00:00,57.0,NaN,NaN
29,56,2025-02-03 08:00:02+00:00,2025-02-03 08:00:16.648000+00:00,2025-02-03 08:00:16.648000+00:00,57.0,NaN,NaN
34,56,2025-02-03 08:01:01+00:00,2025-02-03 08:01:18.019000+00:00,2025-02-03 08:01:18.019000+00:00,56.0,NaN,NaN
39,56,2025-02-03 08:02:02+00:00,2025-02-03 08:02:16.199000+00:00,2025-02-03 08:02:16.199000+00:00,56.0,57.0,NaN
44,56,2025-02-03 08:03:01+00:00,2025-02-03 08:03:16.790000+00:00,2025-02-03 08:03:16.790000+00:00,56.0,57.0,NaN
49,55,2025-02-03 08:04:02+00:00,2025-02-03 08:04:10.791000+00:00,2025-02-03 08:04:10.791000+00:00,56.0,57.0,NaN
54,54,2025-02-03 08:05:01+00:00,2025-02-03 08:05:19.644000+00:00,2025-02-03 08:05:19.644000+00:00,55.0,57.0,NaN
59,54,2025-02-03 08:06:01+00:00,2025-02-03 08:06:05.320000+00:00,2025-02-03 08:06:05.320000+00:00,54.0,57.0,NaN
64,53,2025-02-03 08:09:02+00:00,2025-02-03 08:09:17.615000+00:00,2025-02-03 08:09:17.615000+00:00,54.0,56.0,NaN
69,52,2025-02-03 08:10:02+00:00,2025-02-03 08:10:18.322000+00:00,2025-02-03 08:10:18.322000+00:00,53.0,56.0,NaN
74,52,2025-02-03 08:12:02+00:00,2025-02-03 08:12:17.520000+00:00,2025-02-03 08:12:17.520000+00:00,52.0,56.0,57.0
79,52,2025-02-03 08:13:01+00:00,2025-02-03 08:13:17.739000+00:00,2025-02-03 08:13:17.739000+00:00,52.0,56.0,57.0
84,52,2025-02-03 08:14:02+00:00,2025-02-03 08:14:18.399000+00:00,2025-02-03 08:14:18.399000+00:00,52.0,55.0,57.0
89,52,2025-02-03 08:15:01+00:00,2025-02-03 08:15:13.263000+00:00,2025-02-03 08:15:13.263000+00:00,52.0,54.0,57.0
94,52,2025-02-03 08:16:02+00:00,2025-02-03 08:16:15.222000+00:00,2025-02-03 08:16:15.222000+00:00,52.0,54.0,57.0
99,52,2025-02-03 08:17:01+00:00,2025-02-03 08:17:16.337000+00:00,2025-02-03 08:17:16.337000+00:00,52.0,53.0,56.0